#!/usr/bin/env python3

import argparse
import re
import sys
from pathlib import Path
from tempfile import NamedTemporaryFile

try:
    import tomllib
except ModuleNotFoundError as error:
    raise SystemExit("generate_config.py requires Python 3.11 or newer") from error


SCRIPT_DIR = Path(__file__).resolve().parent
VERILATOR_DIR = SCRIPT_DIR.parent
DEFAULT_CONFIG_PATH = SCRIPT_DIR / "dev.toml"
CONFIG_PATH = VERILATOR_DIR / "config.toml"
OUTPUT_PATH = VERILATOR_DIR / "include" / "generated" / "autoconfig.hh"

CPP_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
DEFCONFIG_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
CPP_KEYWORDS = {
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char16_t",
    "char32_t",
    "class",
    "compl",
    "concept",
    "const",
    "constexpr",
    "const_cast",
    "continue",
    "co_await",
    "co_return",
    "co_yield",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
    "xor",
    "xor_eq",
}


def validate_identifier(name: str, toml_path: str) -> None:
    if not CPP_IDENTIFIER.fullmatch(name) or name in CPP_KEYWORDS:
        raise ValueError(
            f"TOML key '{toml_path}' is not a valid C++ identifier"
        )


def render_table(table: dict[str, object], path: tuple[str, ...], indent: int) -> list[str]:
    lines: list[str] = []
    indentation = " " * indent

    for name, value in table.items():
        item_path = (*path, name)
        dotted_path = ".".join(item_path)
        validate_identifier(name, dotted_path)

        if isinstance(value, dict):
            lines.append(f"{indentation}namespace {name} {{")
            lines.extend(render_table(value, item_path, indent + 4))
            lines.append(f"{indentation}}} // namespace {name}")
        elif type(value) is bool:
            literal = "true" if value else "false"
            lines.append(f"{indentation}constexpr bool {name} = {literal};")
        else:
            raise TypeError(
                f"TOML key '{dotted_path}' must be a boolean, got "
                f"{type(value).__name__}"
            )

    return lines


def generate_header(config: dict[str, object]) -> str:
    lines = [
        "#ifndef NPC_GENERATED_AUTOCONFIG_HH",
        "#define NPC_GENERATED_AUTOCONFIG_HH",
        "",
        "// Generated by config/generate_config.py. Do not edit manually.",
        "namespace config {",
    ]
    lines.extend(render_table(config, (), 4))
    lines.extend(
        [
            "} // namespace config",
            "",
            "#endif // NPC_GENERATED_AUTOCONFIG_HH",
            "",
        ]
    )
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the Verilator C++ configuration header from TOML"
    )
    parser.add_argument(
        "--defconfig",
        default="",
        help="configuration name from config/; accepts names with or without .toml",
    )
    return parser.parse_args()


def resolve_named_config(defconfig: str) -> Path:
    if not DEFCONFIG_NAME.fullmatch(defconfig):
        raise ValueError(
            "DEFCONFIG must be a file name from the config directory"
        )

    filename = defconfig if defconfig.endswith(".toml") else f"{defconfig}.toml"
    candidate = SCRIPT_DIR / filename
    try:
        resolved_candidate = candidate.resolve(strict=True)
    except FileNotFoundError as error:
        raise FileNotFoundError(f"DEFCONFIG not found: {candidate}") from error

    if (
        resolved_candidate.parent != SCRIPT_DIR.resolve()
        or not resolved_candidate.is_file()
    ):
        raise ValueError(f"DEFCONFIG must be a TOML file in {SCRIPT_DIR}")
    return resolved_candidate


def select_source_config(defconfig: str) -> tuple[Path, bool]:
    if defconfig:
        return resolve_named_config(defconfig), True
    if CONFIG_PATH.is_file():
        return CONFIG_PATH, False
    if DEFAULT_CONFIG_PATH.is_file():
        return DEFAULT_CONFIG_PATH, True
    raise FileNotFoundError(f"default config not found: {DEFAULT_CONFIG_PATH}")


def write_bytes_if_changed(path: Path, content: bytes) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == content:
        return False

    with NamedTemporaryFile(
        mode="wb",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as temporary_file:
        temporary_file.write(content)
        temporary_path = Path(temporary_file.name)

    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    temporary_path.chmod(mode)
    temporary_path.replace(path)
    return True


def main() -> int:
    arguments = parse_arguments()
    try:
        source_path, install_config = select_source_config(arguments.defconfig)
        source_content = source_path.read_bytes()
        config = tomllib.loads(source_content.decode("utf-8"))
        header_content = generate_header(config).encode("utf-8")

        if install_config:
            config_changed = write_bytes_if_changed(CONFIG_PATH, source_content)
            action = "Installed" if config_changed else "Selected"
            print(f"{action} config: {source_path} -> {CONFIG_PATH}")

        header_changed = write_bytes_if_changed(OUTPUT_PATH, header_content)
    except (OSError, TypeError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    action = "Generated" if header_changed else "Up to date"
    print(f"{action}: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
